pub(crate) mod adapter;
pub(crate) mod engine;
pub(crate) mod error;
pub(crate) mod ftx;
pub(crate) mod null_adapter;
pub(crate) mod order_request;
pub(crate) mod order_response;

/// Event generated by an exchange - order or balance related
#[derive(Clone, Debug)]
pub enum ExchangeEvent {
    BalanceChange,
    OrderRejected,
    OrderAck,
    OrderFill,
    OrderCancelled,
}

#[derive(Clone, Debug)]
pub enum ExchangeRequest {
    PlaceOrder(order_request::OrderRequest),
    CancelOrder,
}
